# Site settings

title: "Technical Transgressions &#38; Snark"
subtitle: "Viewer discretion advised"

description: > This is my little slice of the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jperrin.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BitIntegrity
github_username:  jperrin
author: Jim Perrin

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - "/vendor/"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "jekyll.thor"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"




# Google analytics
google_analytics: "UA-53433014-1"


